### PR TITLE
Remove autotool builds

### PR DESCRIPTION
**Pull request by andriish**
Remove `autotool` builds.
The reasons:
 - `autotools` are not good in general:
      - not a very portable with poor support of even common compilers
      -  very bloated  -- see the volume of deleted "code" even in this pull request
      - for any non-trivial changes one has to do run the `autoreconf`
      - for releases one has to run `autoreconf` and include the results in the tarball
  - all the functionality is duplicated in the `cmake`
  - the deletion ensures the `cmake` builds will be used -- means there will be `APFELConfig.cmake` installed and the integration of `apfel` with other `cmake` projects will be as simple as 
  ```
 find_package(APFEL)
.....
target_link_libraries(mytarget PRIVATE APFEL::APFEL APFEL::APFELEvol)
```
- the deletion makes possible to make the releases on github in couple clicks -- no need to regenerate the `configure` scripts.

However that is up to you to decide and makes sense only if you are familiar with cmake at least a bit.

### CODE REVIEW

**Review by scarrazza — APPROVED** [review]
Thanks @andriish, I am totally in favour of dropping autotools.

**Review by AleCandido — APPROVED** [review]
I also agree: you're also properly testing CMake, and only the tested workflow should be left (the duplication is not useful).

**Comment by AleCandido** [comment]
@andriish just be aware that there are people packaging APFEL, e.g.

https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/libraries/physics/apfel/default.nix#L22

and they might rely on autotools.

Luckily, they are also clever enough to use a fixed tag (and I believe just a few people are using those packages).

**Comment by andriish** [comment]
Hi @scarrazza , concerning the nixos --I'm sure they will be happy to use CMake. Just because if there are small problems in autotools one has to patch *a lot * of stuff, while for CMake it is just one file.

**Comment by AleCandido** [comment]
I agree, autotools requires a lot more effort to be maintained, and it is less and less used as a build system.

I was just raising the issue of downstream (another example is [myself](https://github.com/NNPDF/workflows/tree/v2/packages/apfel), but of course I can also fix it by myself).

**Pull request merged**
