### PR TITLE
fixing more leaks and segfault

### PR DESCRIPTION
**Pull request by scarrazza**
This PR includes more fixes obtained when compiling APFEL with:
```bash
export FFLAGS="-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fvar-tracking-assignments -pipe -fsanitize=address"
export CXXFLAGS="-fsanitize=address"
export CCFLAGS="-fsanitize=address"
```

### CODE REVIEW

**Comment by scarrazza** [comment]
There still the segfault due to memory:
```
Program received signal SIGSEGV, Segmentation fault.
derivssgqcd (t=0.02640457978183193, 
    m=<error reading variable: value requires 1292832 bytes, which is more than max-value-size>, 
    dmdt=<error reading variable: value requires 1292832 bytes, which is more than max-value-size>)
    at Evolution/odeintsgQCD.f:278
278	      subroutine derivssgQCD(t,M,dMdt)
```

**Comment by scarrazza** [comment]
And here the crash when the truncated solution is enabled:
```bash
Program received signal SIGSEGV, Segmentation fault.
0x00007fff3d1781a3 in truncatedevolveapfel (q20=2.7224999999999997, q2=3.1949374675750732)
    at Evolution/TruncatedEvolveAPFEL.f:8
8	      subroutine TruncatedEvolveAPFEL(Q20,Q2)
```

**Comment by scarrazza** [comment]
So, yes we are getting out of stack:
```
mtau = 1.7769999999999999
inmtau = 'done'
th = 'QCD  '
intheory = 'done'
alpha = <optimized out>
beta = <optimized out>
eps = <error reading variable eps (Cannot access memory at address 0x7ffffdad63a8)>
evolopbkp = <optimized out>
fleptoneps = <error reading variable fleptoneps (Cannot access memory at address 0x7ffffdad66c8)>
fpheps = <error reading variable fpheps (value requires 104520 bytes, which is more than max-value-size)>
ieps = <optimized out>
inf = <optimized out>
ipdf = <optimized out>
jpdf = <optimized out>
mff = <optimized out>
mfi = <optimized out>
mfmax = <optimized out>
mns1 = <error reading variable mns1 (value requires 1616040 bytes, which is more than max-value-size)>
mns2 = <error reading variable mns2 (value requires 1616040 bytes, which is more than max-value-size)>
mns3 = <error reading variable mns3 (value requires 1616040 bytes, which is more than max-value-size)>
mns4 = <error reading variable mns4 (value requires 1616040 bytes, which is more than max-value-size)>
msg1 = <error reading variable msg1 (value requires 25856640 bytes, which is more than max-value-size)>
msg2 = <error reading variable msg2 (value requires 6464160 bytes, which is more than max-value-size)>
mu2f = <error reading variable mu2f (Cannot access memory at address 0x7ffffdad6408)>
mu2i = <error reading variable mu2i (Cannot access memory at address 0x7ffffdad6468)>
pdfsetbkp = '\000' <repeats 24 times>, '\264\256\377\377\377\177\000\000@\221\062\000\060`\000\000\240\254\377\377\377\177\000\000\200\254\377\377\377\177\000\000Ȭ\377\377\377\177\000\000\000\000\000\000\000\000\000\000\300\254\377\377\377\177\000\000\000\346\305\346\361\250.\315Ȭ\377\377\377\177\000\000`\255\377\377'
sign = <optimized out>
```

**Comment by Zaharid** [comment]
Indeed the size of that stack frame for me is around 38 Mb, while the stack limit on the operating system is 10 Mb. You can see that by taking the difference between `$sp` and the position of the stack frame (see it with `info frame` on gdb).

**Comment by Zaharid** [comment]
Some potentially interesting reads:
https://stackoverflow.com/questions/5795938/stack-overflow-in-fortran-90
https://stackoverflow.com/questions/40491424/dynamic-array-in-fortran-77

**Comment by scarrazza** [comment]
Thanks for the links. I managed to avoid the leak only by removing `-fopenmp` and adding `-fno-automatic`. @Zaharid could you please test this PR branch with:

```bash
export FFLAGS="-fno-automatic -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fvar-tracking-assignments -pipe -fsanitize=address"
export CXXFLAGS="-fsanitize=address"
export CCFLAGS="-fsanitize=address"
```

**Comment by scarrazza** [comment]
So, @Zaharid confirms the flag fixes the problem also for him, @vbertone could you please have a look at line 92 of file CachePDFsAPFEL.f, it looks like the index goes outside the m2th array size, after fixing that we can merge this PR.

> At line 92 of file Evolution/CachePDFsAPFEL.f
> Fortran runtime error: Index '7' of dimension 1 of array 'm2th' above upper bound of 6

**Comment by vbertone** [comment]
Stefano, could you please try to replace:

      double precision m2th(4:6)

in src/commons/m2th.h with

      double precision m2th(4:7)

and see if this solves the problem?

**Comment by scarrazza** [comment]
@vbertone after setting to 7 it complains at line 132:

> At line 132 of file Evolution/CachePDFsAPFEL.f
> Fortran runtime error: Index '8' of dimension 1 of array 'm2th' above upper bound of 7

**Comment by vbertone** [comment]
Then try:

  double precision m2th(4:8)

**Comment by scarrazza** [comment]
OK, this works.

**Pull request merged**
